# The services of the project.

mysqldb:
  type: mysql:10.3
  disk: 1536
rediscache:
  type: redis:3.2
elasticsearch:
  type: elasticsearch:7.9
  disk: 256
#solrsearch:
#    type: solr:6.6
#    disk: 1024
